# Generated by Django 5.0 on 2025-01-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_numbers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquenumbers',
            name='number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
